// // // import type { Metadata } from "next";
// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // // }: Readonly<{
// // //   children: React.ReactNode;
// // // }>) {
// // //   return (
// // //     <html lang="en">
// // //       <body
// // //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// // //       >
// // //         {children}
// // //       </body>
// // //     </html>
// // //   );
// // // }

// // import "./globals.css";

// // export const metadata = {
// //   title: "My App",
// //   description: "Global background with bottom SVGs",
// // };

// // export default function RootLayout({ children }: { children: React.ReactNode }) {
// //   return (
// //     <html lang="en">
// //       <body className="min-h-screen relative overflow-hidden bg-[#00354A]">
        
// //         {/* Bottom SVG Layer 1 */}
// //         <img
// //           src="/wave.svg"
// //           alt=""
// //           className="absolute bottom-0 left-0 right-0 w-full pointer-events-none select-none -z-10"
// //         />

// //         {/* Page Content */}
// //         <div className="relative z-20">
// //           {children}
// //         </div>
// //       </body>
// //     </html>
// //   );
// // }
// import "./globals.css";

// export const metadata = {
//   title: "My App",
//   description: "Global Background",
// };

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="min-h-screen relative overflow-hidden">
        
//         {/* Bottom SVG Background (Global for all pages) */}
//         <img
//           src="wave.svg"
//           alt="decorative wave"
//           className="wave-background"
//         />

//         {/* All Page Content */}
//         <main className="relative z-20">
//           {children}
//         </main>
        
//       </body>
//     </html>
//   );
// }
// app/layout.tsx
import "./globals.css";

export const metadata = {
  title: "My App",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#00354A] min-h-screen relative h-screen overflow-y-auto">
        
        <img
          src="wave.svg"
          alt="decorative wave"
          className="wave-background"
        />
        
        {children}
      </body>
    </html>
  );
}

